# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 深度365
email: com360@126.com
description: 深度365
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://com360.github.io" # the base hostname & protocol for your site
twitter_username: no
github_username:  com360

# Build settings
markdown: kramdown

permalink: /blog/:title.html
